<?php
	define("sql_server","localhost");
    define("sql_user","philipsvo");
    define("sql_password","phien93");
	define("sql_database","toeicdb");
	define("BASE_URL","http://localhost/ToeicThi/");
	define("BASE_DIR","/ToeicThi/");
	date_default_timezone_set("Asia/Ho_Chi_Minh");
?>
